name: dominance-gwas
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - xarray
  - dask
  - scikit-learn
  - numba
  - pyarrow
  - matplotlib
  - tqdm
  - bokeh
  - holoviews
  - hvplot
  - datashader
  - colorcet
  - pip
  - pip:
      - -e .
